### ISSUE TITLE
Error while plv8ify lib

### ISSUE THREAD

**Issue by Menzorg** [divyenduz/plv8ify#20]
<img width="1068" alt="Screenshot 2023-03-04 at 15 40 59" src="https://user-images.githubusercontent.com/10159888/222901903-b2225901-5055-40fc-8d0b-6ad8c6055ef7.png">

OS - macOS 12.1
NPM - 6.14.11
Node - 14.15.5
plv8ify - 0.0.39
Command - plv8ify plv8.mathjs.ts
Code plv8.mathjs.ts:
```js
import { atan2 } from 'mathjs';

export function point(one, two) {
  const result = atan2(one, two);
  return result;
}
```

**Comment by divyenduz** [comment]
Thanks for raising this issue, fixed this in #21, released in `plv8ify - 0.0.40`. Please let me know if it doesn't work for you.
