### ISSUE TITLE
start_proc style bundling without having to do `SET plv8.start_proc = plv8ify_init;`

### ISSUE THREAD

**Issue by samwillis** [divyenduz/plv8ify#24]
Currently the 'start_proc' mode does a nice job of bundling all js into one setup function. But the processes of having to do `SET plv8.start_proc = plv8ify_init;` is'nt ideal, and wont be great for usability for a pg_tle extension. 

A possible fix for this it to check if the init has run on each function invocation, and if not run it first:

``` sql
DROP FUNCTION IF EXISTS plv8ify_world();
CREATE OR REPLACE FUNCTION plv8ify_world() RETURNS text AS $plv8ify$

if (globalThis.plv8ify === undefined) {
  plv8.execute('SELECT plv8ify_init();')
}
return globalThis.plv8ify.world()

$plv8ify$ LANGUAGE plv8 IMMUTABLE STRICT;
```

To make this work a small change needs to be made to the init functions to use `globalThis` rather than `this`:

``` sql
DROP FUNCTION IF EXISTS plv8ify_init();
CREATE OR REPLACE FUNCTION plv8ify_init() RETURNS VOID AS $$
globalThis.plv8ify = (() => {
```

**Comment by divyenduz** [comment]
Closing this as #26 is merged.
