### ISSUE TITLE
Included libraries that contain $$ fail script creation

### ISSUE THREAD

**Issue by easel** [divyenduz/plv8ify#3]
Notionally, code like this:

```
var x = "\$$"
```

Will cause the plv8 script processor to early terminate and fail to define the function. Either the $$ needs to be escaped inside the function the script delimiter needs to be switched to something more unique if possible.

**Comment by divyenduz** [comment]
What do you think about this? https://github.com/divyenduz/plv8ify/pull/4

**Comment by easel** [comment]
Looks great! Thanks for digging into it @divyenduz

**Comment by divyenduz** [comment]
Released in 0.0.17
