### ISSUE TITLE
Default to no prefix and/or allow eliminating prefix

### ISSUE THREAD

**Issue by braco** [divyenduz/plv8ify#46]
It doesn't seem like there's a way to eliminate the prefix within —scope-prefix.

This is a surprising behavior that doesn't seem to have a purpose I can imagine, when you can write those prefixes in your own code.

I would argue that the default should be no prefix, and then that config option will still be available to automatically add prefixes.

**Comment by mattiarossi** [comment]
@divyenduz I can take this one, was actually already thinking about it.
We can either go with @braco's proposed behaviour (no prefix by default) or add a new flag, called `--no-scope-prefix`
The new flag option would be better for backwards compatibility, but it is a pretty easy change either way, I have no preference over one or the other ...

**Comment by divyenduz** [comment]
Let's go with @braco's suggestion, we don't care much about backwards compatibility at this stage as we are still in 0.x.x versions! New flag will be more surface area for the API.
