### ISSUE TITLE
Trigger function replacement

### ISSUE THREAD

**Issue by mayrsascha** [divyenduz/plv8ify#48]
In your example you are showing the generated trigger SQL code:

```
DROP FUNCTION IF EXISTS testschema.plv8ify_hello();
CREATE OR REPLACE FUNCTION testschema.plv8ify_hello() RETURNS text AS $plv8ify$
....
$plv8ify$ LANGUAGE plv8 IMMUTABLE STRICT;
```

Question: Why drop the function first? Isn't `CREATE OR REPLACE IF EXISTS` enough to replace that function if it exists? The reason I'm asking is because attempting to drop that function isn't working with the trigger itself still in place.

Show what I currently have to do is:

```
BEGIN;
DROP TRIGGER IF EXISTS function;

CREATE OR REPLACE FUNCTION testschema.plv8ify_hello() RETURNS text AS $plv8ify$
....
$plv8ify$ LANGUAGE plv8 IMMUTABLE STRICT;

CREATE TRIGGER ....
COMMIT;
```

**Comment by divyenduz** [comment]
From the docs: https://www.postgresql.org/docs/current/sql-createfunction.html

> It is not possible to change the name or argument types of a function this way (if you tried, you would actually be creating a new, distinct function).

So, if the TS function arguments change, it creates a new "overloaded" function in PostgreSQL and doesn't delete the old one with the same name. This is unintuitive, therefore I generate code to explicitly remove the function by its name before re-creating it.

I would happily accept a PR to add a flag (`--replace-function`?) to generate the CREATE OR REPLACE variant for functions.

**Comment by mayrsascha** [comment]
Thank you @divyenduz for explaning, it makes sense. I guess this kind of goes beyond the scope of the current library and function overloads can be dangerous/unintuititve even with that flag. I found another solution for myself, but for anyone looking this could probably accomplished by a separate shell command that just removes the first line in the output. So closing this for now.
