### ISSUE TITLE
Bundle mode doesn't work

### ISSUE THREAD

**Issue by ferm10n** [divyenduz/plv8ify#49]
I ran into this while using `--mode bundle`, but saw the same issue is present in the examples.

If I apply the sql files from the [hello-bundle](https://github.com/divyenduz/plv8ify/tree/20edcd11c9b445582ca69de2ca79ad53233c80c3/examples/hello-bundle) and then run
```sql
SELECT myScopehello();
```

I get `ReferenceError: hello is not defined`.

It seems like there's a few issues happening here:
- functions declared in the `myScope_init` are not made available in the global scope.
  - [plv8 documentation is consistent with this](https://github.com/plv8/plv8/blob/83296584ba9cf3c1cedab37fe7cf0cb078264d4e/doc/plv8.md?plain=1#L263-L267)
  
    > The function will be internally defined such that:
    > 
    > (function(arg1, arg2, ..){
    >     $funcbody$
    > })

- functions are checking for `globalThis.myScope === undefined`, but the init function does nothing to define `globalThis.myScope`
- if you don't use the `--scope-prefix` option (and let it be the default of `(empty string)`, then the expression is malformed: `if (globalThis. === undefined) plv8.execute('SELECT myScope_init();');`

-----

Docker Image I'm using for PG - docker.io/library/postgres:14.4-alpine
plv8ify - 0.0.56
plv8 - 3.1.7

**Comment by ferm10n** [comment]
I think it may be related to this section

https://github.com/divyenduz/plv8ify/blob/20edcd11c9b445582ca69de2ca79ad53233c80c3/src/impl/PLV8ifyCLI.ts#L83-L86

But I'm not sure how the replacement is supposed to happen, unless `var myScope = true;` was put in the `input.ts`

**Comment by divyenduz** [comment]
This was likely a regression, thanks for fixing it in your PR.
