### ISSUE TITLE
Please add flag to remove `IMMUTABLE` from function definition

### ISSUE THREAD

**Issue by myemuk** [divyenduz/plv8ify#8]
In case `IMMUTABLE` is added to the function definition it is executed in read-only mode. However some functions are used in order to update rows or insert new records to the table. It will not work with `IMMUTABLE`, so it has to be removed.

Thanks a lot

**Comment by divyenduz** [comment]
Thank you for raising this issue. I am on the move and would probably get to this in some days. But if you have the time, please feel free to raise a PR to add this feature :)
